import { toast } from 'sonner';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: ' Test',
    description: 'Generated by kai',
};
const TestPage = () => {
    return (
        <div>
            {/* <Header name={'qwe'}></Header> */}
            <div>TestPage</div>
            {/* <Image src='/next.svg' width={100} height={100} alt='123'></Image> */}
            {/*toast  */}
            <div>
                <button onClick={() => toast.success('Success!!')}>Give me a toast</button>
            </div>
        </div>
    );
};

export default TestPage;
