import type { Metadata } from 'next';
import { Inter, Agbalumo } from 'next/font/google';
import './globals.css';
import '@radix-ui/themes/styles.css';
//ui

import Navbar from '@/app/components/ui/Navbar';

//
const inter = Inter({ subsets: ['latin'] });
// const agbalumo = Agbalumo({ weight: '400', subsets: ['latin'] });
export const metadata: Metadata = {
    title: ' My Template',
    description: 'Generated by kai',
    //
    // openGraph: {
    //     title: ' My Template',
    //     description: 'Generated by kai',
    //     url: 'google.com',
    //     siteName: 'kTemplate',
    //     images: [{ url: './123.png', width: 500, height: 500 }],
    // },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <Navbar></Navbar>
                <main> {children}</main>
            </body>
        </html>
    );
}
